&lt;link href=&quot;https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css&quot; rel=&quot;stylesheet&quot;&gt;
&lt;!-- Theme CSS --&gt;
&lt;link href=&quot;../assets/css/theme.css&quot; rel=&quot;stylesheet&quot;&gt;

&lt;nav class=&quot;navbar navbar-expand-lg navbar-light bg-light fixed-top&quot;&gt;
    &lt;a class=&quot;navbar-brand&quot; href=&quot;#&quot;&gt;Novatech&lt;/a&gt;
    &lt;button class=&quot;navbar-toggler&quot; type=&quot;button&quot; data-toggle=&quot;collapse&quot; data-target=&quot;#navbarNav&quot; aria-controls=&quot;navbarNav&quot; aria-expanded=&quot;false&quot; aria-label=&quot;Toggle navigation&quot;&gt;
        &lt;span class=&quot;navbar-toggler-icon&quot;&gt;&lt;/span&gt;
    &lt;/button&gt;
    &lt;div class=&quot;collapse navbar-collapse&quot; id=&quot;navbarNav&quot;&gt;
        &lt;ul class=&quot;navbar-nav&quot;&gt;
            &lt;li class=&quot;nav-item active&quot;&gt;
                &lt;a class=&quot;nav-link&quot; href=&quot;client_dashboard&quot;&gt;&lt;i class=&quot;fas fa-tachometer-alt&quot;&gt;&lt;/i&gt; Dashboard&lt;/a&gt;
            &lt;/li&gt;
            &lt;li class=&quot;nav-item&quot;&gt;
                &lt;a class=&quot;nav-link&quot; href=&quot;view_products&quot;&gt;&lt;i class=&quot;fas fa-box-open&quot;&gt;&lt;/i&gt; View Products&lt;/a&gt;
            &lt;/li&gt;
            &lt;li class=&quot;nav-item&quot;&gt;
                &lt;a class=&quot;nav-link&quot; href=&quot;view_investments&quot;&gt;&lt;i class=&quot;fas fa-hand-holding-usd&quot;&gt;&lt;/i&gt; View Investments&lt;/a&gt;
            &lt;/li&gt;
            &lt;li class=&quot;nav-item&quot;&gt;
                &lt;a class=&quot;nav-link&quot; href=&quot;profile&quot;&gt;&lt;i class=&quot;fas fa-user&quot;&gt;&lt;/i&gt; Profile&lt;/a&gt;
            &lt;/li&gt;
            &lt;li class=&quot;nav-item&quot;&gt;
                &lt;a class=&quot;nav-link&quot; href=&quot;invite&quot;&gt;&lt;i class=&quot;fas fa-handshake&quot;&gt;&lt;/i&gt; Invite Friend&lt;/a&gt;
            &lt;/li&gt;
            &lt;li class=&quot;nav-item&quot;&gt;
                &lt;a class=&quot;nav-link&quot; href=&quot;setting&quot;&gt;&lt;i class=&quot;fas fa-cogs&quot;&gt;&lt;/i&gt; Account&lt;/a&gt;
            &lt;/li&gt;
        &lt;/ul&gt;

        &lt;!-- Welcome message and profile image on the right --&gt;
        &lt;ul class=&quot;navbar-nav ml-auto&quot;&gt;
            &lt;li class=&quot;nav-item&quot;&gt;
                &lt;a class=&quot;nav-link ml-3&quot; href=&quot;../auth/logout&quot;&gt;&lt;i class=&quot;fas fa-sign-out-alt&quot;&gt;&lt;/i&gt; Logout&lt;/a&gt;
            &lt;/li&gt;
        &lt;/ul&gt;
    &lt;/div&gt;
&lt;/nav&gt;